export interface IEmployeeResponse{
    id: number,
    name: String,
    phone: String,
    email: String,
    department: String,
    district: String,
    city: String,
    username: String,
    address: String,
    password: String,
    ward: String,
    userID: number,
    permissionID: number,
    active: boolean,
    permission_Name: String,
}